### ISSUE TITLE
Is this library are really need

### ISSUE THREAD

**Issue by fzzr-** [andyli/jQueryExternForHaxe#17]
Sorry if I wrong but now jQuery externs are available in the Haxe's standard library. [JQuery in std](https://github.com/HaxeFoundation/haxe/blob/development/std/js/JQuery.hx).

Is this library are really need?

**Comment by andyli** [comment]
I compared this extern with the one in std in the README file on the [front page](https://github.com/andyli/jQueryExternForHaxe#jsjquery-in-haxe-std-lib-vs-jqueryextern).

And in fact, I'm working on merging this with the one in std lib right now. I described it briefly at the end of [my blog post](http://blog.onthewings.net/2015/06/23/im-now-working-for-the-haxe-foundation/).

**Comment by fzzr-** [comment]
Thanx for answer.
