### ISSUE TITLE
Not working with latest Haxe

### ISSUE THREAD

**Issue by ncannasse** [andyli/jQueryExternForHaxe#25]
Bugs with latest Haxe:
- overload keyword (see #24)
- Config error in macros because `null / 10000` error (should check "jqueryExtern" instead of "jquery_ver")
- can't compile because missing js.jquery.JqIterator (require -lib hx3compat)

**Comment by haxiomic** [comment]
Added some more changes to #24 to address the other failures

- `-D jquery_ver` defaults to jquery 3.3.1 when not specified (same as in haxe previously)
- Copied in the missing iterator fields so that we don't need to depend on hx3compat
