### ISSUE TITLE
Unecessary `new` operators

### ISSUE THREAD

**Issue by mattmccray** [andyli/jQueryExternForHaxe#7]
I'm not sure if this is a bug with this project, or Haxe, but it's inserting a lot of unnecessary `new` operators in the JS output. For example, this:

```haxe
var el= new JQuery('.my-elem');
```

Seems to produce:

```javascript
var el= new $('.my-elem');
```

Note the **`new`** before the **`$`**. The jQuery function isn't a constructor, so this is wasteful (the JS VM will create new objects and apply them to the function each time -- which may not sound like much, but it can add up).

So the desired output is:

```javascript
var el= $('.my-class');
```

Thanks!

**Comment by andyli** [comment]
The latest git version of Haxe has `@:selfCall`, which will suppress generation of `new`.
